### ISSUE TITLE
About feature extraction details of COCO dataset

### ISSUE THREAD

**Issue by ChenBattle** [penghu-cs/SDML#2]
I ran your code and got good results.
Could you please share more feature extraction details of COCO dataset?
Thank you very much!

**Comment by 52hz-j** [comment]
> I ran your code and got good results.
> Could you please share more feature extraction details of COCO dataset?
> Thank you very much!

hello
Where should I download the file wiki_doc2vec_0.mat?
Looking forward to your reply
Thank you very much

**Comment by zt-1026** [comment]
> > 我运行了您的代码，并取得了良好的效果。请您分享 COCO 数据集的更多功能提取详细信息吗？谢谢！
> 
> 你好， 我应该在哪里下载文件wiki_doc2vec_0. mat？期待您的回复非常感谢
hello,Do you find the file wiki_doc2vec_0.mat?If you download it, could you share it with me?
Thank you very much

**Comment by zt-1026** [comment]
> > I ran your code and got good results.
> > Could you please share more feature extraction details of COCO dataset?
> > Thank you very much!
> 
> hello Where should I download the file wiki_doc2vec_0.mat? Looking forward to your reply Thank you very much

hello,Do you find the file wiki_doc2vec_0.mat?If you download it, could you share it with me?
Thank you very much
